// Xscriptor Berlin
colour_set_1 = 000000
colour_set_2 = cccccc
colour_set_3 = aaaaaa
colour_set_4 = 666666
colour_set_5 = 0a0a0a
colour_set_6 = 1f1f1f
colour_set_7 = 999999
colour_set_8 = bbbbbb
colour_set_9 = dddddd
colour_set_10 = 888888
colour_set_11 = cccccc
colour_set_12 = bbbbbb
colour_set_13 = aaaaaa
colour_set_14 = 333333
