// Xscriptor Bogota
colour_set_1 = 200b0a
colour_set_2 = f7f1ff
colour_set_3 = ff9999
colour_set_4 = 8c7e84
colour_set_5 = 2b1616
colour_set_6 = 402e2f
colour_set_7 = fc618d
colour_set_8 = 7bd88f
colour_set_9 = ffed89
colour_set_10 = 47e6ff
colour_set_11 = 47e6ff
colour_set_12 = fc618d
colour_set_13 = ff9999
colour_set_14 = 525053
