// Xscriptor Helsinki
colour_set_1 = f8fafe
colour_set_2 = 544d40
colour_set_3 = 3e9d21
colour_set_4 = 8d8a82
colour_set_5 = f0f1f4
colour_set_6 = dfe0e2
colour_set_7 = 1faa9e
colour_set_8 = 733d9a
colour_set_9 = 2e70ad
colour_set_10 = b55a0f
colour_set_11 = bd4c3d
colour_set_12 = 009e91
colour_set_13 = 3e9d21
colour_set_14 = b0a999
