// Xscriptor Lahabana
colour_set_1 = 19191a
colour_set_2 = f7f1ff
colour_set_3 = 948ae3
colour_set_4 = 67656a
colour_set_5 = 242425
colour_set_6 = 3a393c
colour_set_7 = fc618d
colour_set_8 = 7bd88f
colour_set_9 = e5ff9d
colour_set_10 = fd9353
colour_set_11 = 5ad4e6
colour_set_12 = fc618d
colour_set_13 = 948ae3
colour_set_14 = 19191a
