// Xscriptor Madrid
colour_set_1 = fafafa
colour_set_2 = 1a1a1a
colour_set_3 = 4d2699
colour_set_4 = 4d4d4d
colour_set_5 = efefef
colour_set_6 = d8d8d8
colour_set_7 = 990026
colour_set_8 = 007a28
colour_set_9 = 8a6408
colour_set_10 = 007a9e
colour_set_11 = 007a9e
colour_set_12 = 990026
colour_set_13 = 4d2699
colour_set_14 = 4d4d4d
