// Xscriptor Miami
colour_set_1 = 000000
colour_set_2 = f7f1ff
colour_set_3 = D36CFF
colour_set_4 = 69676c
colour_set_5 = 0c0c0d
colour_set_6 = 252426
colour_set_7 = FF4C8B
colour_set_8 = 7FFFD4
colour_set_9 = FFD84C
colour_set_10 = 00FFA8
colour_set_11 = 47CFFF
colour_set_12 = FF4C8B
colour_set_13 = D36CFF
colour_set_14 = 69676c
