// Xscriptor Paris
colour_set_1 = 1a0a30
colour_set_2 = f7f1ff
colour_set_3 = c4bdff
colour_set_4 = c4bdff
colour_set_5 = 25163a
colour_set_6 = 3b2d4f
colour_set_7 = fc618d
colour_set_8 = 7bd88f
colour_set_9 = fce566
colour_set_10 = a3f3ff
colour_set_11 = a3f3ff
colour_set_12 = fc618d
colour_set_13 = c4bdff
colour_set_14 = c4bdff
