// Xscriptor Praha
colour_set_1 = 1a1a1a
colour_set_2 = ffffff
colour_set_3 = FF9AA2
colour_set_4 = 6272A4
colour_set_5 = 252525
colour_set_6 = 3c3c3c
colour_set_7 = FF5555
colour_set_8 = B8E6A0
colour_set_9 = FFE4A3
colour_set_10 = BD93F9
colour_set_11 = 8BE9FD
colour_set_12 = FF6E6E
colour_set_13 = FF9AA2
colour_set_14 = 6272A4
