// Xscriptor Tokio
colour_set_1 = 1c1c1d
colour_set_2 = f7f1ff
colour_set_3 = 948ae3
colour_set_4 = 69676c
colour_set_5 = 272728
colour_set_6 = 3d3c3f
colour_set_7 = fc618d
colour_set_8 = 7bd88f
colour_set_9 = fce566
colour_set_10 = fd9353
colour_set_11 = 5ad4e6
colour_set_12 = fc618d
colour_set_13 = 948ae3
colour_set_14 = 1c1c1d
