"ui.background" = "#000000"
"ui.foreground" = "#cccccc"
"ui.cursor" = "#aaaaaa"
"ui.cursor.insert" = "#aaaaaa"
"ui.cursor.select" = "#aaaaaa"
"ui.cursor.normal" = "#aaaaaa"
"ui.selection" = "rgba(204, 204, 204, 0.15)"
"ui.linenr" = "#666666"
"ui.linenr.selected" = "#cccccc"
"ui.statusline" = "#000000"
"ui.statusline.inactive" = "#000000"
"ui.popup" = "#000000"
"ui.window" = "#000000"
"ui.help" = "#000000"
"ui.text" = "#cccccc"
"ui.text.focus" = "#cccccc"
"ui.menu" = "#000000"
"ui.menu.selected" = "#aaaaaa"
"ui.virtual.ruler" = "#666666"
"ui.virtual.whitespace" = "#666666"
"keyword" = "#aaaaaa"
"keyword.directive" = "#aaaaaa"
"keyword.control" = "#aaaaaa"
"operator" = "#aaaaaa"
"punctuation" = "#cccccc"
"punctuation.delimiter" = "#666666"
"constant" = "#dddddd"
"constant.numeric" = "#dddddd"
"constant.character.escape" = "#999999"
"string" = "#bbbbbb"
"string.regexp" = "#bbbbbb"
"function" = "#888888"
"function.call" = "#888888"
"function.macro" = "#bbbbbb"
"function.builtin" = "#888888"
"type" = "#cccccc"
"type.builtin" = "#cccccc"
"type.enum" = "#cccccc"
"constructor" = "#cccccc"
"variable" = "#cccccc"
"variable.builtin" = "#999999"
"variable.parameter" = "#888888"
"comment" = "#666666"
"comment.line" = "#666666"
"comment.block" = "#666666"
"markup.heading" = "#cccccc"
"markup.list" = "#999999"
"markup.bold" = "#cccccc"
"markup.italic" = "#cccccc"
"markup.link" = "#cccccc"
"markup.link.text" = "#bbbbbb"
"markup.quote" = "#666666"
"markup.raw" = "#bbbbbb"
"diff.plus" = "#bbbbbb"
"diff.minus" = "#999999"
"diff.delta" = "#dddddd"
"ui.highlight" = "#dddddd"
"ui.highlight.fuzzy" = "#888888"
"warning" = "#dddddd"
"error" = "#999999"
"info" = "#cccccc"
"hint" = "#bbbbbb"
