"ui.background" = "#f8fafe"
"ui.foreground" = "#544d40"
"ui.cursor" = "#3e9d21"
"ui.cursor.insert" = "#3e9d21"
"ui.cursor.select" = "#3e9d21"
"ui.cursor.normal" = "#3e9d21"
"ui.selection" = "rgba(84, 77, 64, 0.15)"
"ui.linenr" = "#8d8a82"
"ui.linenr.selected" = "#544d40"
"ui.statusline" = "#f8fafe"
"ui.statusline.inactive" = "#f8fafe"
"ui.popup" = "#f8fafe"
"ui.window" = "#f8fafe"
"ui.help" = "#f8fafe"
"ui.text" = "#544d40"
"ui.text.focus" = "#544d40"
"ui.menu" = "#f8fafe"
"ui.menu.selected" = "#3e9d21"
"ui.virtual.ruler" = "#8d8a82"
"ui.virtual.whitespace" = "#8d8a82"
"keyword" = "#3e9d21"
"keyword.directive" = "#3e9d21"
"keyword.control" = "#3e9d21"
"operator" = "#3e9d21"
"punctuation" = "#544d40"
"punctuation.delimiter" = "#8d8a82"
"constant" = "#2e70ad"
"constant.numeric" = "#2e70ad"
"constant.character.escape" = "#1faa9e"
"string" = "#733d9a"
"string.regexp" = "#733d9a"
"function" = "#b55a0f"
"function.call" = "#b55a0f"
"function.macro" = "#009e91"
"function.builtin" = "#b55a0f"
"type" = "#bd4c3d"
"type.builtin" = "#bd4c3d"
"type.enum" = "#bd4c3d"
"constructor" = "#bd4c3d"
"variable" = "#544d40"
"variable.builtin" = "#1faa9e"
"variable.parameter" = "#b55a0f"
"comment" = "#8d8a82"
"comment.line" = "#8d8a82"
"comment.block" = "#8d8a82"
"markup.heading" = "#bd4c3d"
"markup.list" = "#1faa9e"
"markup.bold" = "#544d40"
"markup.italic" = "#544d40"
"markup.link" = "#bd4c3d"
"markup.link.text" = "#733d9a"
"markup.quote" = "#8d8a82"
"markup.raw" = "#733d9a"
"diff.plus" = "#733d9a"
"diff.minus" = "#1faa9e"
"diff.delta" = "#2e70ad"
"ui.highlight" = "#2e70ad"
"ui.highlight.fuzzy" = "#b55a0f"
"warning" = "#2e70ad"
"error" = "#1faa9e"
"info" = "#bd4c3d"
"hint" = "#733d9a"
