"ui.background" = "#3f4451"
"ui.foreground" = "#abb2bf"
"ui.cursor" = "#c162de"
"ui.cursor.insert" = "#c162de"
"ui.cursor.select" = "#c162de"
"ui.cursor.normal" = "#c162de"
"ui.selection" = "rgba(171, 178, 191, 0.15)"
"ui.linenr" = "#959ca9"
"ui.linenr.selected" = "#abb2bf"
"ui.statusline" = "#3f4451"
"ui.statusline.inactive" = "#3f4451"
"ui.popup" = "#3f4451"
"ui.window" = "#3f4451"
"ui.help" = "#3f4451"
"ui.text" = "#abb2bf"
"ui.text.focus" = "#abb2bf"
"ui.menu" = "#3f4451"
"ui.menu.selected" = "#c162de"
"ui.virtual.ruler" = "#959ca9"
"ui.virtual.whitespace" = "#959ca9"
"keyword" = "#c162de"
"keyword.directive" = "#c162de"
"keyword.control" = "#c162de"
"operator" = "#c162de"
"punctuation" = "#abb2bf"
"punctuation.delimiter" = "#959ca9"
"constant" = "#d18f52"
"constant.numeric" = "#d18f52"
"constant.character.escape" = "#e05561"
"string" = "#8cc265"
"string.regexp" = "#8cc265"
"function" = "#4aa5f0"
"function.call" = "#4aa5f0"
"function.macro" = "#ff616e"
"function.builtin" = "#4aa5f0"
"type" = "#42b3c2"
"type.builtin" = "#42b3c2"
"type.enum" = "#42b3c2"
"constructor" = "#42b3c2"
"variable" = "#abb2bf"
"variable.builtin" = "#e05561"
"variable.parameter" = "#4aa5f0"
"comment" = "#959ca9"
"comment.line" = "#959ca9"
"comment.block" = "#959ca9"
"markup.heading" = "#42b3c2"
"markup.list" = "#e05561"
"markup.bold" = "#abb2bf"
"markup.italic" = "#abb2bf"
"markup.link" = "#42b3c2"
"markup.link.text" = "#8cc265"
"markup.quote" = "#959ca9"
"markup.raw" = "#8cc265"
"diff.plus" = "#8cc265"
"diff.minus" = "#e05561"
"diff.delta" = "#d18f52"
"ui.highlight" = "#d18f52"
"ui.highlight.fuzzy" = "#4aa5f0"
"warning" = "#d18f52"
"error" = "#e05561"
"info" = "#42b3c2"
"hint" = "#8cc265"
