"ui.background" = "#050505"
"ui.foreground" = "#f7f1ff"
"ui.cursor" = "#948ae3"
"ui.cursor.insert" = "#948ae3"
"ui.cursor.select" = "#948ae3"
"ui.cursor.normal" = "#948ae3"
"ui.selection" = "rgba(247, 241, 255, 0.15)"
"ui.linenr" = "#7e7b82"
"ui.linenr.selected" = "#f7f1ff"
"ui.statusline" = "#050505"
"ui.statusline.inactive" = "#0a0a0a"
"ui.popup" = "#050505"
"ui.window" = "#0a0a0a"
"ui.help" = "#050505"
"ui.text" = "#f7f1ff"
"ui.text.focus" = "#f7f1ff"
"ui.menu" = "#050505"
"ui.menu.selected" = "#948ae3"
"ui.virtual.ruler" = "#7e7b82"
"ui.virtual.whitespace" = "#7e7b82"
"keyword" = "#948ae3"
"keyword.directive" = "#948ae3"
"keyword.control" = "#948ae3"
"operator" = "#948ae3"
"punctuation" = "#f7f1ff"
"punctuation.delimiter" = "#7e7b82"
"constant" = "#fce566"
"constant.numeric" = "#fce566"
"constant.character.escape" = "#fc618d"
"string" = "#7bd88f"
"string.regexp" = "#7bd88f"
"function" = "#fd9353"
"function.call" = "#fd9353"
"function.macro" = "#fc618d"
"function.builtin" = "#fd9353"
"type" = "#5ad4e6"
"type.builtin" = "#5ad4e6"
"type.enum" = "#5ad4e6"
"constructor" = "#5ad4e6"
"variable" = "#f7f1ff"
"variable.builtin" = "#fc618d"
"variable.parameter" = "#fd9353"
"comment" = "#7e7b82"
"comment.line" = "#7e7b82"
"comment.block" = "#7e7b82"
"markup.heading" = "#5ad4e6"
"markup.list" = "#fc618d"
"markup.bold" = "#f7f1ff"
"markup.italic" = "#f7f1ff"
"markup.link" = "#5ad4e6"
"markup.link.text" = "#7bd88f"
"markup.quote" = "#7e7b82"
"markup.raw" = "#7bd88f"
"diff.plus" = "#7bd88f"
"diff.minus" = "#fc618d"
"diff.delta" = "#fce566"
"ui.highlight" = "#fce566"
"ui.highlight.fuzzy" = "#fd9353"
"warning" = "#fce566"
"error" = "#fc618d"
"info" = "#5ad4e6"
"hint" = "#7bd88f"
