;;; xscriptor-x-theme.el --- Xscriptor X theme

(deftheme xscriptor-x
  "Xscriptor X theme")

(let ((class '((class color) (min-colors 89))))
  (custom-theme-set-faces
   'xscriptor-x
   `(default ((,class (:background "#050505" :foreground "#f7f1ff"))))
   `(cursor ((,class (:background "#948ae3"))))
   `(region ((,class (:background "rgba(247, 241, 255, 0.15)"))))
   `(fringe ((,class (:background "#050505"))))
   `(linum ((,class (:foreground "#7e7b82" :background "#050505"))))
   `(line-number ((,class (:foreground "#7e7b82" :background "#050505"))))
   `(line-number-current-line ((,class (:foreground "#948ae3" :background "#111112"))))
   `(mode-line ((,class (:background "#0a0a0a" :foreground "#f7f1ff"))))
   `(mode-line-inactive ((,class (:background "#0a0a0a" :foreground "#7e7b82"))))
   `(minibuffer-prompt ((,class (:foreground "#948ae3"))))
   `(font-lock-comment-face ((,class (:foreground "#7e7b82" :italic t))))
   `(font-lock-comment-delimiter-face ((,class (:foreground "#7e7b82" :italic t))))
   `(font-lock-string-face ((,class (:foreground "#7bd88f"))))
   `(font-lock-doc-face ((,class (:foreground "#7bd88f"))))
   `(font-lock-doc-markup-face ((,class (:foreground "#7bd88f"))))
   `(font-lock-keyword-face ((,class (:foreground "#948ae3"))))
   `(font-lock-builtin-face ((,class (:foreground "#5ad4e6"))))
   `(font-lock-function-name-face ((,class (:foreground "#fd9353"))))
   `(font-lock-variable-name-face ((,class (:foreground "#f7f1ff"))))
   `(font-lock-type-face ((,class (:foreground "#5ad4e6"))))
   `(font-lock-constant-face ((,class (:foreground "#fce566"))))
   `(font-lock-warning-face ((,class (:foreground "#fce566"))))
   `(font-lock-preprocessor-face ((,class (:foreground "#fc618d"))))
   `(font-lock-negation-char-face ((,class (:foreground "#948ae3"))))
   `(font-lock-regexp-grouping-backslash ((,class (:foreground "#fc618d"))))
   `(font-lock-regexp-grouping-construct ((,class (:foreground "#fc618d"))))
   `(highlight ((,class (:background "#111112"))))
   `(match ((,class (:background "#fce566" :foreground "#050505"))))
   `(isearch ((,class (:background "#fce566" :foreground "#050505"))))
   `(lazy-highlight ((,class (:background "rgba(252, 229, 102, 0.3)"))))
   `(show-paren-match ((,class (:background "#948ae3"))))
   `(show-paren-mismatch ((,class (:background "#fc618d"))))
   `(link ((,class (:foreground "#5ad4e6" :underline t))))
   `(button ((,class (:underline t :foreground "#5ad4e6"))))
   `(success ((,class (:foreground "#7bd88f"))))
   `(warning ((,class (:foreground "#fce566"))))
   `(error ((,class (:foreground "#fc618d"))))
   `(header-line ((,class (:background "#111112" :foreground "#f7f1ff"))))
   `(trailing-whitespace ((,class (:background "#fc618d"))))
   `(whitespace-space ((,class (:foreground "#7e7b82" :background "#050505"))))
   `(whitespace-tab ((,class (:foreground "#7e7b82" :background "#050505"))))
   `(whitespace-newline ((,class (:foreground "#7e7b82"))))
   `(whitespace-trailing ((,class (:background "#fc618d"))))
   `(dired-directory ((,class (:foreground "#5ad4e6"))))
   `(dired-header ((,class (:foreground "#fd9353"))))
   `(dired-marked ((,class (:foreground "#948ae3"))))
   `(diff-added ((,class (:foreground "#7bd88f"))))
   `(diff-changed ((,class (:foreground "#fce566"))))
   `(diff-removed ((,class (:foreground "#fc618d"))))
   `(diff-refine-added ((,class (:foreground "#7bd88f" :background "#050505"))))
   `(diff-refine-changed ((,class (:foreground "#fce566" :background "#050505"))))
   `(diff-refine-removed ((,class (:foreground "#fc618d" :background "#050505"))))
   `(magit-section-highlight ((,class (:background "#111112"))))
   `(magit-diff-added ((,class (:foreground "#7bd88f"))))
   `(magit-diff-removed ((,class (:foreground "#fc618d"))))
   ))

(provide-theme 'xscriptor-x)
;;; xscriptor-x-theme.el ends here
