;;; xscriptor-lahabana-theme.el --- Xscriptor Lahabana theme

(deftheme xscriptor-lahabana
  "Xscriptor Lahabana theme")

(let ((class '((class color) (min-colors 89))))
  (custom-theme-set-faces
   'xscriptor-lahabana
   `(default ((,class (:background "#19191a" :foreground "#f7f1ff"))))
   `(cursor ((,class (:background "#948ae3"))))
   `(region ((,class (:background "rgba(247, 241, 255, 0.15)"))))
   `(fringe ((,class (:background "#19191a"))))
   `(linum ((,class (:foreground "#67656a" :background "#19191a"))))
   `(line-number ((,class (:foreground "#67656a" :background "#19191a"))))
   `(line-number-current-line ((,class (:foreground "#948ae3" :background "#242425"))))
   `(mode-line ((,class (:background "#19191a" :foreground "#f7f1ff"))))
   `(mode-line-inactive ((,class (:background "#19191a" :foreground "#67656a"))))
   `(minibuffer-prompt ((,class (:foreground "#948ae3"))))
   `(font-lock-comment-face ((,class (:foreground "#67656a" :italic t))))
   `(font-lock-comment-delimiter-face ((,class (:foreground "#67656a" :italic t))))
   `(font-lock-string-face ((,class (:foreground "#7bd88f"))))
   `(font-lock-doc-face ((,class (:foreground "#7bd88f"))))
   `(font-lock-doc-markup-face ((,class (:foreground "#7bd88f"))))
   `(font-lock-keyword-face ((,class (:foreground "#948ae3"))))
   `(font-lock-builtin-face ((,class (:foreground "#5ad4e6"))))
   `(font-lock-function-name-face ((,class (:foreground "#fd9353"))))
   `(font-lock-variable-name-face ((,class (:foreground "#f7f1ff"))))
   `(font-lock-type-face ((,class (:foreground "#5ad4e6"))))
   `(font-lock-constant-face ((,class (:foreground "#e5ff9d"))))
   `(font-lock-warning-face ((,class (:foreground "#e5ff9d"))))
   `(font-lock-preprocessor-face ((,class (:foreground "#fc618d"))))
   `(font-lock-negation-char-face ((,class (:foreground "#948ae3"))))
   `(font-lock-regexp-grouping-backslash ((,class (:foreground "#fc618d"))))
   `(font-lock-regexp-grouping-construct ((,class (:foreground "#fc618d"))))
   `(highlight ((,class (:background "#242425"))))
   `(match ((,class (:background "#e5ff9d" :foreground "#19191a"))))
   `(isearch ((,class (:background "#e5ff9d" :foreground "#19191a"))))
   `(lazy-highlight ((,class (:background "rgba(229, 255, 157, 0.3)"))))
   `(show-paren-match ((,class (:background "#948ae3"))))
   `(show-paren-mismatch ((,class (:background "#fc618d"))))
   `(link ((,class (:foreground "#5ad4e6" :underline t))))
   `(button ((,class (:underline t :foreground "#5ad4e6"))))
   `(success ((,class (:foreground "#7bd88f"))))
   `(warning ((,class (:foreground "#e5ff9d"))))
   `(error ((,class (:foreground "#fc618d"))))
   `(header-line ((,class (:background "#242425" :foreground "#f7f1ff"))))
   `(trailing-whitespace ((,class (:background "#fc618d"))))
   `(whitespace-space ((,class (:foreground "#67656a" :background "#19191a"))))
   `(whitespace-tab ((,class (:foreground "#67656a" :background "#19191a"))))
   `(whitespace-newline ((,class (:foreground "#67656a"))))
   `(whitespace-trailing ((,class (:background "#fc618d"))))
   `(dired-directory ((,class (:foreground "#5ad4e6"))))
   `(dired-header ((,class (:foreground "#fd9353"))))
   `(dired-marked ((,class (:foreground "#948ae3"))))
   `(diff-added ((,class (:foreground "#7bd88f"))))
   `(diff-changed ((,class (:foreground "#e5ff9d"))))
   `(diff-removed ((,class (:foreground "#fc618d"))))
   `(diff-refine-added ((,class (:foreground "#7bd88f" :background "#19191a"))))
   `(diff-refine-changed ((,class (:foreground "#e5ff9d" :background "#19191a"))))
   `(diff-refine-removed ((,class (:foreground "#fc618d" :background "#19191a"))))
   `(magit-section-highlight ((,class (:background "#242425"))))
   `(magit-diff-added ((,class (:foreground "#7bd88f"))))
   `(magit-diff-removed ((,class (:foreground "#fc618d"))))
   ))

(provide-theme 'xscriptor-lahabana)
;;; xscriptor-lahabana-theme.el ends here
