;;; xscriptor-miami-theme.el --- Xscriptor Miami theme

(deftheme xscriptor-miami
  "Xscriptor Miami theme")

(let ((class '((class color) (min-colors 89))))
  (custom-theme-set-faces
   'xscriptor-miami
   `(default ((,class (:background "#000000" :foreground "#f7f1ff"))))
   `(cursor ((,class (:background "#D36CFF"))))
   `(region ((,class (:background "rgba(247, 241, 255, 0.15)"))))
   `(fringe ((,class (:background "#000000"))))
   `(linum ((,class (:foreground "#69676c" :background "#000000"))))
   `(line-number ((,class (:foreground "#69676c" :background "#000000"))))
   `(line-number-current-line ((,class (:foreground "#D36CFF" :background "#0c0c0d"))))
   `(mode-line ((,class (:background "#000000" :foreground "#f7f1ff"))))
   `(mode-line-inactive ((,class (:background "#000000" :foreground "#69676c"))))
   `(minibuffer-prompt ((,class (:foreground "#D36CFF"))))
   `(font-lock-comment-face ((,class (:foreground "#69676c" :italic t))))
   `(font-lock-comment-delimiter-face ((,class (:foreground "#69676c" :italic t))))
   `(font-lock-string-face ((,class (:foreground "#7FFFD4"))))
   `(font-lock-doc-face ((,class (:foreground "#7FFFD4"))))
   `(font-lock-doc-markup-face ((,class (:foreground "#7FFFD4"))))
   `(font-lock-keyword-face ((,class (:foreground "#D36CFF"))))
   `(font-lock-builtin-face ((,class (:foreground "#47CFFF"))))
   `(font-lock-function-name-face ((,class (:foreground "#00FFA8"))))
   `(font-lock-variable-name-face ((,class (:foreground "#f7f1ff"))))
   `(font-lock-type-face ((,class (:foreground "#47CFFF"))))
   `(font-lock-constant-face ((,class (:foreground "#FFD84C"))))
   `(font-lock-warning-face ((,class (:foreground "#FFD84C"))))
   `(font-lock-preprocessor-face ((,class (:foreground "#FF4C8B"))))
   `(font-lock-negation-char-face ((,class (:foreground "#D36CFF"))))
   `(font-lock-regexp-grouping-backslash ((,class (:foreground "#FF4C8B"))))
   `(font-lock-regexp-grouping-construct ((,class (:foreground "#FF4C8B"))))
   `(highlight ((,class (:background "#0c0c0d"))))
   `(match ((,class (:background "#FFD84C" :foreground "#000000"))))
   `(isearch ((,class (:background "#FFD84C" :foreground "#000000"))))
   `(lazy-highlight ((,class (:background "rgba(255, 216, 76, 0.3)"))))
   `(show-paren-match ((,class (:background "#D36CFF"))))
   `(show-paren-mismatch ((,class (:background "#FF4C8B"))))
   `(link ((,class (:foreground "#47CFFF" :underline t))))
   `(button ((,class (:underline t :foreground "#47CFFF"))))
   `(success ((,class (:foreground "#7FFFD4"))))
   `(warning ((,class (:foreground "#FFD84C"))))
   `(error ((,class (:foreground "#FF4C8B"))))
   `(header-line ((,class (:background "#0c0c0d" :foreground "#f7f1ff"))))
   `(trailing-whitespace ((,class (:background "#FF4C8B"))))
   `(whitespace-space ((,class (:foreground "#69676c" :background "#000000"))))
   `(whitespace-tab ((,class (:foreground "#69676c" :background "#000000"))))
   `(whitespace-newline ((,class (:foreground "#69676c"))))
   `(whitespace-trailing ((,class (:background "#FF4C8B"))))
   `(dired-directory ((,class (:foreground "#47CFFF"))))
   `(dired-header ((,class (:foreground "#00FFA8"))))
   `(dired-marked ((,class (:foreground "#D36CFF"))))
   `(diff-added ((,class (:foreground "#7FFFD4"))))
   `(diff-changed ((,class (:foreground "#FFD84C"))))
   `(diff-removed ((,class (:foreground "#FF4C8B"))))
   `(diff-refine-added ((,class (:foreground "#7FFFD4" :background "#000000"))))
   `(diff-refine-changed ((,class (:foreground "#FFD84C" :background "#000000"))))
   `(diff-refine-removed ((,class (:foreground "#FF4C8B" :background "#000000"))))
   `(magit-section-highlight ((,class (:background "#0c0c0d"))))
   `(magit-diff-added ((,class (:foreground "#7FFFD4"))))
   `(magit-diff-removed ((,class (:foreground "#FF4C8B"))))
   ))

(provide-theme 'xscriptor-miami)
;;; xscriptor-miami-theme.el ends here
