;;; xscriptor-helsinki-theme.el --- Xscriptor Helsinki theme

(deftheme xscriptor-helsinki
  "Xscriptor Helsinki theme")

(let ((class '((class color) (min-colors 89))))
  (custom-theme-set-faces
   'xscriptor-helsinki
   `(default ((,class (:background "#f8fafe" :foreground "#544d40"))))
   `(cursor ((,class (:background "#3e9d21"))))
   `(region ((,class (:background "rgba(84, 77, 64, 0.15)"))))
   `(fringe ((,class (:background "#f8fafe"))))
   `(linum ((,class (:foreground "#8d8a82" :background "#f8fafe"))))
   `(line-number ((,class (:foreground "#8d8a82" :background "#f8fafe"))))
   `(line-number-current-line ((,class (:foreground "#3e9d21" :background "#f0f1f4"))))
   `(mode-line ((,class (:background "#f8fafe" :foreground "#544d40"))))
   `(mode-line-inactive ((,class (:background "#f8fafe" :foreground "#8d8a82"))))
   `(minibuffer-prompt ((,class (:foreground "#3e9d21"))))
   `(font-lock-comment-face ((,class (:foreground "#8d8a82" :italic t))))
   `(font-lock-comment-delimiter-face ((,class (:foreground "#8d8a82" :italic t))))
   `(font-lock-string-face ((,class (:foreground "#733d9a"))))
   `(font-lock-doc-face ((,class (:foreground "#733d9a"))))
   `(font-lock-doc-markup-face ((,class (:foreground "#733d9a"))))
   `(font-lock-keyword-face ((,class (:foreground "#3e9d21"))))
   `(font-lock-builtin-face ((,class (:foreground "#bd4c3d"))))
   `(font-lock-function-name-face ((,class (:foreground "#b55a0f"))))
   `(font-lock-variable-name-face ((,class (:foreground "#544d40"))))
   `(font-lock-type-face ((,class (:foreground "#bd4c3d"))))
   `(font-lock-constant-face ((,class (:foreground "#2e70ad"))))
   `(font-lock-warning-face ((,class (:foreground "#2e70ad"))))
   `(font-lock-preprocessor-face ((,class (:foreground "#009e91"))))
   `(font-lock-negation-char-face ((,class (:foreground "#3e9d21"))))
   `(font-lock-regexp-grouping-backslash ((,class (:foreground "#1faa9e"))))
   `(font-lock-regexp-grouping-construct ((,class (:foreground "#1faa9e"))))
   `(highlight ((,class (:background "#f0f1f4"))))
   `(match ((,class (:background "#2e70ad" :foreground "#f8fafe"))))
   `(isearch ((,class (:background "#2e70ad" :foreground "#f8fafe"))))
   `(lazy-highlight ((,class (:background "rgba(46, 112, 173, 0.3)"))))
   `(show-paren-match ((,class (:background "#3e9d21"))))
   `(show-paren-mismatch ((,class (:background "#1faa9e"))))
   `(link ((,class (:foreground "#bd4c3d" :underline t))))
   `(button ((,class (:underline t :foreground "#bd4c3d"))))
   `(success ((,class (:foreground "#733d9a"))))
   `(warning ((,class (:foreground "#2e70ad"))))
   `(error ((,class (:foreground "#1faa9e"))))
   `(header-line ((,class (:background "#f0f1f4" :foreground "#544d40"))))
   `(trailing-whitespace ((,class (:background "#1faa9e"))))
   `(whitespace-space ((,class (:foreground "#8d8a82" :background "#f8fafe"))))
   `(whitespace-tab ((,class (:foreground "#8d8a82" :background "#f8fafe"))))
   `(whitespace-newline ((,class (:foreground "#8d8a82"))))
   `(whitespace-trailing ((,class (:background "#1faa9e"))))
   `(dired-directory ((,class (:foreground "#bd4c3d"))))
   `(dired-header ((,class (:foreground "#b55a0f"))))
   `(dired-marked ((,class (:foreground "#3e9d21"))))
   `(diff-added ((,class (:foreground "#733d9a"))))
   `(diff-changed ((,class (:foreground "#2e70ad"))))
   `(diff-removed ((,class (:foreground "#1faa9e"))))
   `(diff-refine-added ((,class (:foreground "#733d9a" :background "#f8fafe"))))
   `(diff-refine-changed ((,class (:foreground "#2e70ad" :background "#f8fafe"))))
   `(diff-refine-removed ((,class (:foreground "#1faa9e" :background "#f8fafe"))))
   `(magit-section-highlight ((,class (:background "#f0f1f4"))))
   `(magit-diff-added ((,class (:foreground "#733d9a"))))
   `(magit-diff-removed ((,class (:foreground "#1faa9e"))))
   ))

(provide-theme 'xscriptor-helsinki)
;;; xscriptor-helsinki-theme.el ends here
