;;; xscriptor-madrid-theme.el --- Xscriptor Madrid theme

(deftheme xscriptor-madrid
  "Xscriptor Madrid theme")

(let ((class '((class color) (min-colors 89))))
  (custom-theme-set-faces
   'xscriptor-madrid
   `(default ((,class (:background "#fafafa" :foreground "#1a1a1a"))))
   `(cursor ((,class (:background "#4d2699"))))
   `(region ((,class (:background "rgba(26, 26, 26, 0.15)"))))
   `(fringe ((,class (:background "#fafafa"))))
   `(linum ((,class (:foreground "#4d4d4d" :background "#fafafa"))))
   `(line-number ((,class (:foreground "#4d4d4d" :background "#fafafa"))))
   `(line-number-current-line ((,class (:foreground "#4d2699" :background "#efefef"))))
   `(mode-line ((,class (:background "#fafafa" :foreground "#1a1a1a"))))
   `(mode-line-inactive ((,class (:background "#fafafa" :foreground "#4d4d4d"))))
   `(minibuffer-prompt ((,class (:foreground "#4d2699"))))
   `(font-lock-comment-face ((,class (:foreground "#4d4d4d" :italic t))))
   `(font-lock-comment-delimiter-face ((,class (:foreground "#4d4d4d" :italic t))))
   `(font-lock-string-face ((,class (:foreground "#007a28"))))
   `(font-lock-doc-face ((,class (:foreground "#007a28"))))
   `(font-lock-doc-markup-face ((,class (:foreground "#007a28"))))
   `(font-lock-keyword-face ((,class (:foreground "#4d2699"))))
   `(font-lock-builtin-face ((,class (:foreground "#007a9e"))))
   `(font-lock-function-name-face ((,class (:foreground "#007a9e"))))
   `(font-lock-variable-name-face ((,class (:foreground "#1a1a1a"))))
   `(font-lock-type-face ((,class (:foreground "#007a9e"))))
   `(font-lock-constant-face ((,class (:foreground "#8a6408"))))
   `(font-lock-warning-face ((,class (:foreground "#8a6408"))))
   `(font-lock-preprocessor-face ((,class (:foreground "#990026"))))
   `(font-lock-negation-char-face ((,class (:foreground "#4d2699"))))
   `(font-lock-regexp-grouping-backslash ((,class (:foreground "#990026"))))
   `(font-lock-regexp-grouping-construct ((,class (:foreground "#990026"))))
   `(highlight ((,class (:background "#efefef"))))
   `(match ((,class (:background "#8a6408" :foreground "#fafafa"))))
   `(isearch ((,class (:background "#8a6408" :foreground "#fafafa"))))
   `(lazy-highlight ((,class (:background "rgba(138, 100, 8, 0.3)"))))
   `(show-paren-match ((,class (:background "#4d2699"))))
   `(show-paren-mismatch ((,class (:background "#990026"))))
   `(link ((,class (:foreground "#007a9e" :underline t))))
   `(button ((,class (:underline t :foreground "#007a9e"))))
   `(success ((,class (:foreground "#007a28"))))
   `(warning ((,class (:foreground "#8a6408"))))
   `(error ((,class (:foreground "#990026"))))
   `(header-line ((,class (:background "#efefef" :foreground "#1a1a1a"))))
   `(trailing-whitespace ((,class (:background "#990026"))))
   `(whitespace-space ((,class (:foreground "#4d4d4d" :background "#fafafa"))))
   `(whitespace-tab ((,class (:foreground "#4d4d4d" :background "#fafafa"))))
   `(whitespace-newline ((,class (:foreground "#4d4d4d"))))
   `(whitespace-trailing ((,class (:background "#990026"))))
   `(dired-directory ((,class (:foreground "#007a9e"))))
   `(dired-header ((,class (:foreground "#007a9e"))))
   `(dired-marked ((,class (:foreground "#4d2699"))))
   `(diff-added ((,class (:foreground "#007a28"))))
   `(diff-changed ((,class (:foreground "#8a6408"))))
   `(diff-removed ((,class (:foreground "#990026"))))
   `(diff-refine-added ((,class (:foreground "#007a28" :background "#fafafa"))))
   `(diff-refine-changed ((,class (:foreground "#8a6408" :background "#fafafa"))))
   `(diff-refine-removed ((,class (:foreground "#990026" :background "#fafafa"))))
   `(magit-section-highlight ((,class (:background "#efefef"))))
   `(magit-diff-added ((,class (:foreground "#007a28"))))
   `(magit-diff-removed ((,class (:foreground "#990026"))))
   ))

(provide-theme 'xscriptor-madrid)
;;; xscriptor-madrid-theme.el ends here
