;;; xscriptor-bogota-theme.el --- Xscriptor Bogota theme

(deftheme xscriptor-bogota
  "Xscriptor Bogota theme")

(let ((class '((class color) (min-colors 89))))
  (custom-theme-set-faces
   'xscriptor-bogota
   `(default ((,class (:background "#200b0a" :foreground "#f7f1ff"))))
   `(cursor ((,class (:background "#ff9999"))))
   `(region ((,class (:background "rgba(247, 241, 255, 0.15)"))))
   `(fringe ((,class (:background "#200b0a"))))
   `(linum ((,class (:foreground "#8c7e84" :background "#200b0a"))))
   `(line-number ((,class (:foreground "#8c7e84" :background "#200b0a"))))
   `(line-number-current-line ((,class (:foreground "#ff9999" :background "#2b1616"))))
   `(mode-line ((,class (:background "#200b0a" :foreground "#f7f1ff"))))
   `(mode-line-inactive ((,class (:background "#200b0a" :foreground "#8c7e84"))))
   `(minibuffer-prompt ((,class (:foreground "#ff9999"))))
   `(font-lock-comment-face ((,class (:foreground "#8c7e84" :italic t))))
   `(font-lock-comment-delimiter-face ((,class (:foreground "#8c7e84" :italic t))))
   `(font-lock-string-face ((,class (:foreground "#7bd88f"))))
   `(font-lock-doc-face ((,class (:foreground "#7bd88f"))))
   `(font-lock-doc-markup-face ((,class (:foreground "#7bd88f"))))
   `(font-lock-keyword-face ((,class (:foreground "#ff9999"))))
   `(font-lock-builtin-face ((,class (:foreground "#47e6ff"))))
   `(font-lock-function-name-face ((,class (:foreground "#47e6ff"))))
   `(font-lock-variable-name-face ((,class (:foreground "#f7f1ff"))))
   `(font-lock-type-face ((,class (:foreground "#47e6ff"))))
   `(font-lock-constant-face ((,class (:foreground "#ffed89"))))
   `(font-lock-warning-face ((,class (:foreground "#ffed89"))))
   `(font-lock-preprocessor-face ((,class (:foreground "#fc618d"))))
   `(font-lock-negation-char-face ((,class (:foreground "#ff9999"))))
   `(font-lock-regexp-grouping-backslash ((,class (:foreground "#fc618d"))))
   `(font-lock-regexp-grouping-construct ((,class (:foreground "#fc618d"))))
   `(highlight ((,class (:background "#2b1616"))))
   `(match ((,class (:background "#ffed89" :foreground "#200b0a"))))
   `(isearch ((,class (:background "#ffed89" :foreground "#200b0a"))))
   `(lazy-highlight ((,class (:background "rgba(255, 237, 137, 0.3)"))))
   `(show-paren-match ((,class (:background "#ff9999"))))
   `(show-paren-mismatch ((,class (:background "#fc618d"))))
   `(link ((,class (:foreground "#47e6ff" :underline t))))
   `(button ((,class (:underline t :foreground "#47e6ff"))))
   `(success ((,class (:foreground "#7bd88f"))))
   `(warning ((,class (:foreground "#ffed89"))))
   `(error ((,class (:foreground "#fc618d"))))
   `(header-line ((,class (:background "#2b1616" :foreground "#f7f1ff"))))
   `(trailing-whitespace ((,class (:background "#fc618d"))))
   `(whitespace-space ((,class (:foreground "#8c7e84" :background "#200b0a"))))
   `(whitespace-tab ((,class (:foreground "#8c7e84" :background "#200b0a"))))
   `(whitespace-newline ((,class (:foreground "#8c7e84"))))
   `(whitespace-trailing ((,class (:background "#fc618d"))))
   `(dired-directory ((,class (:foreground "#47e6ff"))))
   `(dired-header ((,class (:foreground "#47e6ff"))))
   `(dired-marked ((,class (:foreground "#ff9999"))))
   `(diff-added ((,class (:foreground "#7bd88f"))))
   `(diff-changed ((,class (:foreground "#ffed89"))))
   `(diff-removed ((,class (:foreground "#fc618d"))))
   `(diff-refine-added ((,class (:foreground "#7bd88f" :background "#200b0a"))))
   `(diff-refine-changed ((,class (:foreground "#ffed89" :background "#200b0a"))))
   `(diff-refine-removed ((,class (:foreground "#fc618d" :background "#200b0a"))))
   `(magit-section-highlight ((,class (:background "#2b1616"))))
   `(magit-diff-added ((,class (:foreground "#7bd88f"))))
   `(magit-diff-removed ((,class (:foreground "#fc618d"))))
   ))

(provide-theme 'xscriptor-bogota)
;;; xscriptor-bogota-theme.el ends here
