;;; xscriptor-paris-theme.el --- Xscriptor Paris theme

(deftheme xscriptor-paris
  "Xscriptor Paris theme")

(let ((class '((class color) (min-colors 89))))
  (custom-theme-set-faces
   'xscriptor-paris
   `(default ((,class (:background "#1a0a30" :foreground "#f7f1ff"))))
   `(cursor ((,class (:background "#c4bdff"))))
   `(region ((,class (:background "rgba(247, 241, 255, 0.15)"))))
   `(fringe ((,class (:background "#1a0a30"))))
   `(linum ((,class (:foreground "#c4bdff" :background "#1a0a30"))))
   `(line-number ((,class (:foreground "#c4bdff" :background "#1a0a30"))))
   `(line-number-current-line ((,class (:foreground "#c4bdff" :background "#25163a"))))
   `(mode-line ((,class (:background "#1a0a30" :foreground "#f7f1ff"))))
   `(mode-line-inactive ((,class (:background "#1a0a30" :foreground "#c4bdff"))))
   `(minibuffer-prompt ((,class (:foreground "#c4bdff"))))
   `(font-lock-comment-face ((,class (:foreground "#c4bdff" :italic t))))
   `(font-lock-comment-delimiter-face ((,class (:foreground "#c4bdff" :italic t))))
   `(font-lock-string-face ((,class (:foreground "#7bd88f"))))
   `(font-lock-doc-face ((,class (:foreground "#7bd88f"))))
   `(font-lock-doc-markup-face ((,class (:foreground "#7bd88f"))))
   `(font-lock-keyword-face ((,class (:foreground "#c4bdff"))))
   `(font-lock-builtin-face ((,class (:foreground "#a3f3ff"))))
   `(font-lock-function-name-face ((,class (:foreground "#a3f3ff"))))
   `(font-lock-variable-name-face ((,class (:foreground "#f7f1ff"))))
   `(font-lock-type-face ((,class (:foreground "#a3f3ff"))))
   `(font-lock-constant-face ((,class (:foreground "#fce566"))))
   `(font-lock-warning-face ((,class (:foreground "#fce566"))))
   `(font-lock-preprocessor-face ((,class (:foreground "#fc618d"))))
   `(font-lock-negation-char-face ((,class (:foreground "#c4bdff"))))
   `(font-lock-regexp-grouping-backslash ((,class (:foreground "#fc618d"))))
   `(font-lock-regexp-grouping-construct ((,class (:foreground "#fc618d"))))
   `(highlight ((,class (:background "#25163a"))))
   `(match ((,class (:background "#fce566" :foreground "#1a0a30"))))
   `(isearch ((,class (:background "#fce566" :foreground "#1a0a30"))))
   `(lazy-highlight ((,class (:background "rgba(252, 229, 102, 0.3)"))))
   `(show-paren-match ((,class (:background "#c4bdff"))))
   `(show-paren-mismatch ((,class (:background "#fc618d"))))
   `(link ((,class (:foreground "#a3f3ff" :underline t))))
   `(button ((,class (:underline t :foreground "#a3f3ff"))))
   `(success ((,class (:foreground "#7bd88f"))))
   `(warning ((,class (:foreground "#fce566"))))
   `(error ((,class (:foreground "#fc618d"))))
   `(header-line ((,class (:background "#25163a" :foreground "#f7f1ff"))))
   `(trailing-whitespace ((,class (:background "#fc618d"))))
   `(whitespace-space ((,class (:foreground "#c4bdff" :background "#1a0a30"))))
   `(whitespace-tab ((,class (:foreground "#c4bdff" :background "#1a0a30"))))
   `(whitespace-newline ((,class (:foreground "#c4bdff"))))
   `(whitespace-trailing ((,class (:background "#fc618d"))))
   `(dired-directory ((,class (:foreground "#a3f3ff"))))
   `(dired-header ((,class (:foreground "#a3f3ff"))))
   `(dired-marked ((,class (:foreground "#c4bdff"))))
   `(diff-added ((,class (:foreground "#7bd88f"))))
   `(diff-changed ((,class (:foreground "#fce566"))))
   `(diff-removed ((,class (:foreground "#fc618d"))))
   `(diff-refine-added ((,class (:foreground "#7bd88f" :background "#1a0a30"))))
   `(diff-refine-changed ((,class (:foreground "#fce566" :background "#1a0a30"))))
   `(diff-refine-removed ((,class (:foreground "#fc618d" :background "#1a0a30"))))
   `(magit-section-highlight ((,class (:background "#25163a"))))
   `(magit-diff-added ((,class (:foreground "#7bd88f"))))
   `(magit-diff-removed ((,class (:foreground "#fc618d"))))
   ))

(provide-theme 'xscriptor-paris)
;;; xscriptor-paris-theme.el ends here
