;;; xscriptor-praha-theme.el --- Xscriptor Praha theme

(deftheme xscriptor-praha
  "Xscriptor Praha theme")

(let ((class '((class color) (min-colors 89))))
  (custom-theme-set-faces
   'xscriptor-praha
   `(default ((,class (:background "#1a1a1a" :foreground "#ffffff"))))
   `(cursor ((,class (:background "#FF9AA2"))))
   `(region ((,class (:background "rgba(255, 255, 255, 0.15)"))))
   `(fringe ((,class (:background "#1a1a1a"))))
   `(linum ((,class (:foreground "#6272A4" :background "#1a1a1a"))))
   `(line-number ((,class (:foreground "#6272A4" :background "#1a1a1a"))))
   `(line-number-current-line ((,class (:foreground "#FF9AA2" :background "#252525"))))
   `(mode-line ((,class (:background "#1A1A1A" :foreground "#ffffff"))))
   `(mode-line-inactive ((,class (:background "#1A1A1A" :foreground "#6272A4"))))
   `(minibuffer-prompt ((,class (:foreground "#FF9AA2"))))
   `(font-lock-comment-face ((,class (:foreground "#6272A4" :italic t))))
   `(font-lock-comment-delimiter-face ((,class (:foreground "#6272A4" :italic t))))
   `(font-lock-string-face ((,class (:foreground "#B8E6A0"))))
   `(font-lock-doc-face ((,class (:foreground "#B8E6A0"))))
   `(font-lock-doc-markup-face ((,class (:foreground "#B8E6A0"))))
   `(font-lock-keyword-face ((,class (:foreground "#FF9AA2"))))
   `(font-lock-builtin-face ((,class (:foreground "#8BE9FD"))))
   `(font-lock-function-name-face ((,class (:foreground "#BD93F9"))))
   `(font-lock-variable-name-face ((,class (:foreground "#ffffff"))))
   `(font-lock-type-face ((,class (:foreground "#8BE9FD"))))
   `(font-lock-constant-face ((,class (:foreground "#FFE4A3"))))
   `(font-lock-warning-face ((,class (:foreground "#FFE4A3"))))
   `(font-lock-preprocessor-face ((,class (:foreground "#FF6E6E"))))
   `(font-lock-negation-char-face ((,class (:foreground "#FF9AA2"))))
   `(font-lock-regexp-grouping-backslash ((,class (:foreground "#FF5555"))))
   `(font-lock-regexp-grouping-construct ((,class (:foreground "#FF5555"))))
   `(highlight ((,class (:background "#252525"))))
   `(match ((,class (:background "#FFE4A3" :foreground "#1a1a1a"))))
   `(isearch ((,class (:background "#FFE4A3" :foreground "#1a1a1a"))))
   `(lazy-highlight ((,class (:background "rgba(255, 228, 163, 0.3)"))))
   `(show-paren-match ((,class (:background "#FF9AA2"))))
   `(show-paren-mismatch ((,class (:background "#FF5555"))))
   `(link ((,class (:foreground "#8BE9FD" :underline t))))
   `(button ((,class (:underline t :foreground "#8BE9FD"))))
   `(success ((,class (:foreground "#B8E6A0"))))
   `(warning ((,class (:foreground "#FFE4A3"))))
   `(error ((,class (:foreground "#FF5555"))))
   `(header-line ((,class (:background "#252525" :foreground "#ffffff"))))
   `(trailing-whitespace ((,class (:background "#FF5555"))))
   `(whitespace-space ((,class (:foreground "#6272A4" :background "#1a1a1a"))))
   `(whitespace-tab ((,class (:foreground "#6272A4" :background "#1a1a1a"))))
   `(whitespace-newline ((,class (:foreground "#6272A4"))))
   `(whitespace-trailing ((,class (:background "#FF5555"))))
   `(dired-directory ((,class (:foreground "#8BE9FD"))))
   `(dired-header ((,class (:foreground "#BD93F9"))))
   `(dired-marked ((,class (:foreground "#FF9AA2"))))
   `(diff-added ((,class (:foreground "#B8E6A0"))))
   `(diff-changed ((,class (:foreground "#FFE4A3"))))
   `(diff-removed ((,class (:foreground "#FF5555"))))
   `(diff-refine-added ((,class (:foreground "#B8E6A0" :background "#1a1a1a"))))
   `(diff-refine-changed ((,class (:foreground "#FFE4A3" :background "#1a1a1a"))))
   `(diff-refine-removed ((,class (:foreground "#FF5555" :background "#1a1a1a"))))
   `(magit-section-highlight ((,class (:background "#252525"))))
   `(magit-diff-added ((,class (:foreground "#B8E6A0"))))
   `(magit-diff-removed ((,class (:foreground "#FF5555"))))
   ))

(provide-theme 'xscriptor-praha)
;;; xscriptor-praha-theme.el ends here
