;;; xscriptor-berlin-theme.el --- Xscriptor Berlin theme

(deftheme xscriptor-berlin
  "Xscriptor Berlin theme")

(let ((class '((class color) (min-colors 89))))
  (custom-theme-set-faces
   'xscriptor-berlin
   `(default ((,class (:background "#000000" :foreground "#cccccc"))))
   `(cursor ((,class (:background "#aaaaaa"))))
   `(region ((,class (:background "rgba(204, 204, 204, 0.15)"))))
   `(fringe ((,class (:background "#000000"))))
   `(linum ((,class (:foreground "#666666" :background "#000000"))))
   `(line-number ((,class (:foreground "#666666" :background "#000000"))))
   `(line-number-current-line ((,class (:foreground "#aaaaaa" :background "#0a0a0a"))))
   `(mode-line ((,class (:background "#000000" :foreground "#cccccc"))))
   `(mode-line-inactive ((,class (:background "#000000" :foreground "#666666"))))
   `(minibuffer-prompt ((,class (:foreground "#aaaaaa"))))
   `(font-lock-comment-face ((,class (:foreground "#666666" :italic t))))
   `(font-lock-comment-delimiter-face ((,class (:foreground "#666666" :italic t))))
   `(font-lock-string-face ((,class (:foreground "#bbbbbb"))))
   `(font-lock-doc-face ((,class (:foreground "#bbbbbb"))))
   `(font-lock-doc-markup-face ((,class (:foreground "#bbbbbb"))))
   `(font-lock-keyword-face ((,class (:foreground "#aaaaaa"))))
   `(font-lock-builtin-face ((,class (:foreground "#cccccc"))))
   `(font-lock-function-name-face ((,class (:foreground "#888888"))))
   `(font-lock-variable-name-face ((,class (:foreground "#cccccc"))))
   `(font-lock-type-face ((,class (:foreground "#cccccc"))))
   `(font-lock-constant-face ((,class (:foreground "#dddddd"))))
   `(font-lock-warning-face ((,class (:foreground "#dddddd"))))
   `(font-lock-preprocessor-face ((,class (:foreground "#bbbbbb"))))
   `(font-lock-negation-char-face ((,class (:foreground "#aaaaaa"))))
   `(font-lock-regexp-grouping-backslash ((,class (:foreground "#999999"))))
   `(font-lock-regexp-grouping-construct ((,class (:foreground "#999999"))))
   `(highlight ((,class (:background "#0a0a0a"))))
   `(match ((,class (:background "#dddddd" :foreground "#000000"))))
   `(isearch ((,class (:background "#dddddd" :foreground "#000000"))))
   `(lazy-highlight ((,class (:background "rgba(221, 221, 221, 0.3)"))))
   `(show-paren-match ((,class (:background "#aaaaaa"))))
   `(show-paren-mismatch ((,class (:background "#999999"))))
   `(link ((,class (:foreground "#cccccc" :underline t))))
   `(button ((,class (:underline t :foreground "#cccccc"))))
   `(success ((,class (:foreground "#bbbbbb"))))
   `(warning ((,class (:foreground "#dddddd"))))
   `(error ((,class (:foreground "#999999"))))
   `(header-line ((,class (:background "#0a0a0a" :foreground "#cccccc"))))
   `(trailing-whitespace ((,class (:background "#999999"))))
   `(whitespace-space ((,class (:foreground "#666666" :background "#000000"))))
   `(whitespace-tab ((,class (:foreground "#666666" :background "#000000"))))
   `(whitespace-newline ((,class (:foreground "#666666"))))
   `(whitespace-trailing ((,class (:background "#999999"))))
   `(dired-directory ((,class (:foreground "#cccccc"))))
   `(dired-header ((,class (:foreground "#888888"))))
   `(dired-marked ((,class (:foreground "#aaaaaa"))))
   `(diff-added ((,class (:foreground "#bbbbbb"))))
   `(diff-changed ((,class (:foreground "#dddddd"))))
   `(diff-removed ((,class (:foreground "#999999"))))
   `(diff-refine-added ((,class (:foreground "#bbbbbb" :background "#000000"))))
   `(diff-refine-changed ((,class (:foreground "#dddddd" :background "#000000"))))
   `(diff-refine-removed ((,class (:foreground "#999999" :background "#000000"))))
   `(magit-section-highlight ((,class (:background "#0a0a0a"))))
   `(magit-diff-added ((,class (:foreground "#bbbbbb"))))
   `(magit-diff-removed ((,class (:foreground "#999999"))))
   ))

(provide-theme 'xscriptor-berlin)
;;; xscriptor-berlin-theme.el ends here
