;;; xscriptor-oslo-theme.el --- Xscriptor Oslo theme

(deftheme xscriptor-oslo
  "Xscriptor Oslo theme")

(let ((class '((class color) (min-colors 89))))
  (custom-theme-set-faces
   'xscriptor-oslo
   `(default ((,class (:background "#3f4451" :foreground "#abb2bf"))))
   `(cursor ((,class (:background "#c162de"))))
   `(region ((,class (:background "rgba(171, 178, 191, 0.15)"))))
   `(fringe ((,class (:background "#3f4451"))))
   `(linum ((,class (:foreground "#959ca9" :background "#3f4451"))))
   `(line-number ((,class (:foreground "#959ca9" :background "#3f4451"))))
   `(line-number-current-line ((,class (:foreground "#c162de" :background "#444a56"))))
   `(mode-line ((,class (:background "#3f4451" :foreground "#abb2bf"))))
   `(mode-line-inactive ((,class (:background "#3f4451" :foreground "#959ca9"))))
   `(minibuffer-prompt ((,class (:foreground "#c162de"))))
   `(font-lock-comment-face ((,class (:foreground "#959ca9" :italic t))))
   `(font-lock-comment-delimiter-face ((,class (:foreground "#959ca9" :italic t))))
   `(font-lock-string-face ((,class (:foreground "#8cc265"))))
   `(font-lock-doc-face ((,class (:foreground "#8cc265"))))
   `(font-lock-doc-markup-face ((,class (:foreground "#8cc265"))))
   `(font-lock-keyword-face ((,class (:foreground "#c162de"))))
   `(font-lock-builtin-face ((,class (:foreground "#42b3c2"))))
   `(font-lock-function-name-face ((,class (:foreground "#4aa5f0"))))
   `(font-lock-variable-name-face ((,class (:foreground "#abb2bf"))))
   `(font-lock-type-face ((,class (:foreground "#42b3c2"))))
   `(font-lock-constant-face ((,class (:foreground "#d18f52"))))
   `(font-lock-warning-face ((,class (:foreground "#d18f52"))))
   `(font-lock-preprocessor-face ((,class (:foreground "#ff616e"))))
   `(font-lock-negation-char-face ((,class (:foreground "#c162de"))))
   `(font-lock-regexp-grouping-backslash ((,class (:foreground "#e05561"))))
   `(font-lock-regexp-grouping-construct ((,class (:foreground "#e05561"))))
   `(highlight ((,class (:background "#444a56"))))
   `(match ((,class (:background "#d18f52" :foreground "#3f4451"))))
   `(isearch ((,class (:background "#d18f52" :foreground "#3f4451"))))
   `(lazy-highlight ((,class (:background "rgba(209, 143, 82, 0.3)"))))
   `(show-paren-match ((,class (:background "#c162de"))))
   `(show-paren-mismatch ((,class (:background "#e05561"))))
   `(link ((,class (:foreground "#42b3c2" :underline t))))
   `(button ((,class (:underline t :foreground "#42b3c2"))))
   `(success ((,class (:foreground "#8cc265"))))
   `(warning ((,class (:foreground "#d18f52"))))
   `(error ((,class (:foreground "#e05561"))))
   `(header-line ((,class (:background "#444a56" :foreground "#abb2bf"))))
   `(trailing-whitespace ((,class (:background "#e05561"))))
   `(whitespace-space ((,class (:foreground "#959ca9" :background "#3f4451"))))
   `(whitespace-tab ((,class (:foreground "#959ca9" :background "#3f4451"))))
   `(whitespace-newline ((,class (:foreground "#959ca9"))))
   `(whitespace-trailing ((,class (:background "#e05561"))))
   `(dired-directory ((,class (:foreground "#42b3c2"))))
   `(dired-header ((,class (:foreground "#4aa5f0"))))
   `(dired-marked ((,class (:foreground "#c162de"))))
   `(diff-added ((,class (:foreground "#8cc265"))))
   `(diff-changed ((,class (:foreground "#d18f52"))))
   `(diff-removed ((,class (:foreground "#e05561"))))
   `(diff-refine-added ((,class (:foreground "#8cc265" :background "#3f4451"))))
   `(diff-refine-changed ((,class (:foreground "#d18f52" :background "#3f4451"))))
   `(diff-refine-removed ((,class (:foreground "#e05561" :background "#3f4451"))))
   `(magit-section-highlight ((,class (:background "#444a56"))))
   `(magit-diff-added ((,class (:foreground "#8cc265"))))
   `(magit-diff-removed ((,class (:foreground "#e05561"))))
   ))

(provide-theme 'xscriptor-oslo)
;;; xscriptor-oslo-theme.el ends here
