;;; xscriptor-london-theme.el --- Xscriptor London theme

(deftheme xscriptor-london
  "Xscriptor London theme")

(let ((class '((class color) (min-colors 89))))
  (custom-theme-set-faces
   'xscriptor-london
   `(default ((,class (:background "#ffffff" :foreground "#333333"))))
   `(cursor ((,class (:background "#777777"))))
   `(region ((,class (:background "rgba(51, 51, 51, 0.15)"))))
   `(fringe ((,class (:background "#ffffff"))))
   `(linum ((,class (:foreground "#333333" :background "#ffffff"))))
   `(line-number ((,class (:foreground "#333333" :background "#ffffff"))))
   `(line-number-current-line ((,class (:foreground "#777777" :background "#f5f5f5"))))
   `(mode-line ((,class (:background "#ffffff" :foreground "#333333"))))
   `(mode-line-inactive ((,class (:background "#ffffff" :foreground "#333333"))))
   `(minibuffer-prompt ((,class (:foreground "#777777"))))
   `(font-lock-comment-face ((,class (:foreground "#333333" :italic t))))
   `(font-lock-comment-delimiter-face ((,class (:foreground "#333333" :italic t))))
   `(font-lock-string-face ((,class (:foreground "#444444"))))
   `(font-lock-doc-face ((,class (:foreground "#444444"))))
   `(font-lock-doc-markup-face ((,class (:foreground "#444444"))))
   `(font-lock-keyword-face ((,class (:foreground "#777777"))))
   `(font-lock-builtin-face ((,class (:foreground "#888888"))))
   `(font-lock-function-name-face ((,class (:foreground "#666666"))))
   `(font-lock-variable-name-face ((,class (:foreground "#333333"))))
   `(font-lock-type-face ((,class (:foreground "#888888"))))
   `(font-lock-constant-face ((,class (:foreground "#555555"))))
   `(font-lock-warning-face ((,class (:foreground "#555555"))))
   `(font-lock-preprocessor-face ((,class (:foreground "#444444"))))
   `(font-lock-negation-char-face ((,class (:foreground "#777777"))))
   `(font-lock-regexp-grouping-backslash ((,class (:foreground "#333333"))))
   `(font-lock-regexp-grouping-construct ((,class (:foreground "#333333"))))
   `(highlight ((,class (:background "#f5f5f5"))))
   `(match ((,class (:background "#555555" :foreground "#ffffff"))))
   `(isearch ((,class (:background "#555555" :foreground "#ffffff"))))
   `(lazy-highlight ((,class (:background "rgba(85, 85, 85, 0.3)"))))
   `(show-paren-match ((,class (:background "#777777"))))
   `(show-paren-mismatch ((,class (:background "#333333"))))
   `(link ((,class (:foreground "#888888" :underline t))))
   `(button ((,class (:underline t :foreground "#888888"))))
   `(success ((,class (:foreground "#444444"))))
   `(warning ((,class (:foreground "#555555"))))
   `(error ((,class (:foreground "#333333"))))
   `(header-line ((,class (:background "#f5f5f5" :foreground "#333333"))))
   `(trailing-whitespace ((,class (:background "#333333"))))
   `(whitespace-space ((,class (:foreground "#333333" :background "#ffffff"))))
   `(whitespace-tab ((,class (:foreground "#333333" :background "#ffffff"))))
   `(whitespace-newline ((,class (:foreground "#333333"))))
   `(whitespace-trailing ((,class (:background "#333333"))))
   `(dired-directory ((,class (:foreground "#888888"))))
   `(dired-header ((,class (:foreground "#666666"))))
   `(dired-marked ((,class (:foreground "#777777"))))
   `(diff-added ((,class (:foreground "#444444"))))
   `(diff-changed ((,class (:foreground "#555555"))))
   `(diff-removed ((,class (:foreground "#333333"))))
   `(diff-refine-added ((,class (:foreground "#444444" :background "#ffffff"))))
   `(diff-refine-changed ((,class (:foreground "#555555" :background "#ffffff"))))
   `(diff-refine-removed ((,class (:foreground "#333333" :background "#ffffff"))))
   `(magit-section-highlight ((,class (:background "#f5f5f5"))))
   `(magit-diff-added ((,class (:foreground "#444444"))))
   `(magit-diff-removed ((,class (:foreground "#333333"))))
   ))

(provide-theme 'xscriptor-london)
;;; xscriptor-london-theme.el ends here
